Temporary breakpoint 1 at 0x40052a: file macto_test.c, line 7.
Starting program: /media/caoyin/work/iApply/gdb/gdb_script/macto_test 

Temporary breakpoint 1, main () at macto_test.c:7
7	  printf ("Hello %s\n", NAME);
Exception ignored in: <gdb.GdbOutputFile object at 0x7f48ed2b5a20>
Traceback (most recent call last):
  File "/usr/share/gdb/python/gdb/__init__.py", line 43, in flush
    def flush(self):
KeyboardInterrupt
